SUGGESTIONS = {"align-content": ["baseline", "center", "end", "flex-end", "flex-start",
"inherit", "initial", "last baseline", "left", "normal", "right",
"space-around", "space-between", "space-evenly", "start", "stretch", "unset"],
"align-items": ["baseline", "center", "end", "flex-end", "flex-start",
"inherit", "initial", "last baseline", "left", "normal", "right", "self-end",
"self-start", "start", "stretch", "unset"], "align-self": ["auto", "baseline",
"center", "end", "flex-end", "flex-start", "inherit", "initial", "last baseline",
"left", "normal", "right", "self-end", "self-start", "start",
"stretch", "unset"], "all": ["COLOR", "absolute", "active", "add", "alias",
"all", "all-petite-caps", "all-scroll", "all-small-caps", "alpha", "alphabetic",
"alternate", "alternate-reverse", "always", "auto", "avoid", "backwards",
"balance", "baseline", "bevel", "blink", "block", "block-axis", "bold",
"bolder", "border-box", "both", "bottom", "bottom-outside", "break-all",
"break-word", "butt", "button", "button-arrow-down", "button-arrow-next",
"button-arrow-previous", "button-arrow-up", "button-bevel", "button-focus",
"calc", "capitalize", "caption", "caret", "cell", "center", "central",
"checkbox", "checkbox-container", "checkbox-label", "checkmenuitem", "clip",
"clone", "close-quote", "col-resize", "collapse", "color", "color-burn",
"color-dodge", "column", "column-reverse", "common-ligatures", "condensed",
"contain", "content-box", "contents", "context-fill", "context-fill-opacity",
"context-menu", "context-stroke", "context-stroke-opacity", "context-value",
"contextual", "copy", "cover", "crispedges", "crosshair", "cubic-bezier",
"currentColor", "darken", "dashed", "default", "dense", "diagonal-fractions",
"dialog", "difference", "digits", "disabled", "discretionary-ligatures",
"distribute", "dotted", "double", "drag", "dualbutton", "e-resize", "ease",
"ease-in", "ease-in-out", "ease-out", "economy", "element", "elements",
"ellipsis", "enabled", "end", "evenodd", "ew-resize", "exact", "exclude",
"exclusion", "expanded", "extra-condensed", "extra-expanded", "fill",
"fill-box", "fixed", "flat", "flex", "flex-end", "flex-start", "flip",
"flow-root", "forwards", "from-image", "full-width", "geometricprecision",
"grab", "grabbing", "grayscale", "grid", "groove", "groupbox", "hanging",
"hard-light", "help", "hidden", "hide", "historical-forms",
"historical-ligatures", "horizontal", "horizontal-tb", "hsl", "hsla", "hue",
"icon", "ideographic", "ignore", "ignore-horizontal", "ignore-vertical",
"inactive", "infinite", "inherit", "initial", "inline", "inline-axis",
"inline-block", "inline-end", "inline-flex", "inline-grid", "inline-start",
"inline-table", "inset", "inside", "inter-character", "inter-word", "intersect",
"isolate", "italic", "jis04", "jis78", "jis83", "jis90", "justify", "keep-all",
"large", "larger", "last baseline", "left", "lighten", "lighter",
"line-through", "linear", "linear-gradient", "linearrgb", "lining-nums",
"list-item", "listbox", "listitem", "local", "lowercase", "lr", "lr-tb",
"luminance", "luminosity", "mandatory", "manipulation", "manual", "margin-box",
"match-source", "mathematical", "max-content", "medium", "menu", "menuarrow",
"menubar", "menucheckbox", "menuimage", "menuitem", "menuitemtext", "menulist",
"menulist-button", "menulist-text", "menulist-textfield", "menupopup",
"menuradio", "menuseparator", "message-box", "meterbar", "meterchunk", "middle",
"min-content", "miter", "mixed", "move", "multiply", "n-resize", "ne-resize",
"nesw-resize", "no-change", "no-clip", "no-close-quote", "no-common-ligatures",
"no-contextual", "no-discretionary-ligatures", "no-drag", "no-drop",
"no-historical-ligatures", "no-open-quote", "no-repeat", "non-scaling-stroke",
"none", "nonzero", "normal", "not-allowed", "nowrap", "ns-resize",
"number-input", "nw-resize", "nwse-resize", "oblique", "oldstyle-nums",
"open-quote", "optimizelegibility", "optimizequality", "optimizespeed",
"ordinal", "outset", "outside", "over", "overlay", "overline", "padding-box",
"painted", "pan-x", "pan-y", "paused", "petite-caps", "pointer", "pre",
"pre-line", "pre-wrap", "preserve-3d", "progress", "progressbar",
"progressbar-vertical", "progresschunk", "progresschunk-vertical",
"proportional-nums", "proportional-width", "proximity", "radial-gradient",
"radio", "radio-container", "radio-label", "radiomenuitem", "range",
"range-thumb", "read-only", "read-write", "relative", "repeat", "repeat-x",
"repeat-y", "repeating-linear-gradient", "repeating-radial-gradient",
"reset-size", "resizer", "resizerpanel", "reverse", "rgb", "rgba", "ridge",
"right", "rl", "rl-tb", "round", "row", "row-resize", "row-reverse", "ruby",
"ruby-base", "ruby-base-container", "ruby-text", "ruby-text-container",
"running", "s-resize", "saturation", "scale-down", "scale-horizontal",
"scale-vertical", "scalethumb-horizontal", "scalethumb-vertical",
"scalethumbend", "scalethumbstart", "scalethumbtick", "screen", "scroll",
"scrollbar", "scrollbar-horizontal", "scrollbar-small", "scrollbar-vertical",
"scrollbarbutton-down", "scrollbarbutton-left", "scrollbarbutton-right",
"scrollbarbutton-up", "scrollbarthumb-horizontal", "scrollbarthumb-vertical",
"scrollbartrack-horizontal", "scrollbartrack-vertical", "se-resize",
"searchfield", "select-after", "select-all", "select-before", "select-menu",
"select-same", "self-end", "self-start", "semi-condensed", "semi-expanded",
"separate", "separator", "show", "sideways", "sideways-lr", "sideways-right",
"sideways-rl", "simplified", "slashed-zero", "slice", "small", "small-caps",
"small-caption", "smaller", "smooth", "soft-light", "solid", "space",
"space-around", "space-between", "space-evenly", "spinner",
"spinner-downbutton", "spinner-textfield", "spinner-upbutton", "splitter",
"square", "srgb", "stacked-fractions", "start", "static", "status-bar",
"statusbar", "statusbarpanel", "step-end", "step-start", "steps", "sticky",
"stretch", "stretch-to-fit", "stroke", "stroke-box", "style", "sub", "subtract",
"super", "sw-resize", "tab", "tab-scroll-arrow-back",
"tab-scroll-arrow-forward", "table", "table-caption", "table-cell",
"table-column", "table-column-group", "table-footer-group",
"table-header-group", "table-row", "table-row-group", "tabpanel", "tabpanels",
"tabular-nums", "tb", "tb-rl", "text", "text-after-edge", "text-before-edge",
"text-bottom", "text-top", "textfield", "textfield-multiline", "thick", "thin",
"titling-caps", "toggle", "toolbar", "toolbarbutton", "toolbarbutton-dropdown",
"toolbargripper", "toolbox", "tooltip", "top", "top-outside", "traditional",
"transparent", "treeheader", "treeheadercell", "treeheadersortarrow",
"treeitem", "treeline", "treetwisty", "treetwistyopen", "treeview", "tri-state",
"ultra-condensed", "ultra-expanded", "under", "underline", "unicase", "unset",
"uppercase", "upright", "url", "use-script", "vertical", "vertical-lr",
"vertical-rl", "vertical-text", "view-box", "visible", "visiblefill",
"visiblepainted", "visiblestroke", "w-resize", "wait", "wavy", "weight",
"window", "wrap", "wrap-reverse", "write-only", "x-large", "x-small",
"xx-large", "xx-small", "zoom-in", "zoom-out"], "animation": ["alternate",
"alternate-reverse", "backwards", "both", "cubic-bezier", "ease", "ease-in",
"ease-in-out", "ease-out", "forwards", "infinite", "inherit", "initial",
"linear", "none", "normal", "paused", "reverse", "running", "step-end",
"step-start", "steps", "unset"], "animation-delay": ["inherit", "initial",
"unset"], "animation-direction": ["alternate", "alternate-reverse", "inherit",
"initial", "normal", "reverse", "unset"], "animation-duration": ["inherit",
"initial", "unset"], "animation-fill-mode": ["backwards", "both", "forwards",
"inherit", "initial", "none", "unset"], "animation-iteration-count":
["infinite", "inherit", "initial", "unset"], "animation-name": ["inherit",
"initial", "none", "unset"], "animation-play-state": ["inherit", "initial",
"paused", "running", "unset"], "animation-timing-function": ["cubic-bezier",
"ease", "ease-in", "ease-in-out", "ease-out", "inherit", "initial", "linear",
"step-end", "step-start", "steps", "unset"], "backface-visibility": ["hidden",
"inherit", "initial", "unset", "visible"], "background": ["COLOR", "border-box",
"bottom", "center", "contain", "content-box", "cover", "currentColor", "fixed",
"hsl", "hsla", "inherit", "initial", "left", "linear-gradient", "local",
"no-repeat", "none", "padding-box", "radial-gradient", "repeat", "repeat-x",
"repeat-y", "repeating-linear-gradient", "repeating-radial-gradient", "rgb",
"rgba", "right", "round", "scroll", "space", "text", "top", "transparent",
"unset", "url"], "background-attachment": ["fixed", "inherit", "initial",
"local", "scroll", "unset"], "background-blend-mode": ["color", "color-burn",
"color-dodge", "darken", "difference", "exclusion", "hard-light", "hue",
"inherit", "initial", "lighten", "luminosity", "multiply", "normal", "overlay",
"saturation", "screen", "soft-light", "unset"], "background-clip":
["border-box", "content-box", "inherit", "initial", "padding-box", "text",
"unset"], "background-color": ["COLOR", "currentColor", "hsl", "hsla",
"inherit", "initial", "rgb", "rgba", "transparent", "unset"],
"background-image": ["inherit", "initial", "linear-gradient", "none",
"radial-gradient", "repeating-linear-gradient", "repeating-radial-gradient",
"unset", "url"], "background-origin": ["border-box", "content-box", "inherit",
"initial", "padding-box", "unset"], "background-position": ["bottom", "center",
"inherit", "initial", "left", "right", "top", "unset"], "background-position-x":
["bottom", "center", "inherit", "initial", "left", "right", "top", "unset"],
"background-position-y": ["bottom", "center", "inherit", "initial", "left",
"right", "top", "unset"], "background-repeat": ["inherit", "initial",
"no-repeat", "repeat", "repeat-x", "repeat-y", "round", "space", "unset"],
"background-size": ["contain", "cover", "inherit", "initial", "unset"],
"block-size": ["auto", "calc", "inherit", "initial", "unset"], "border":
["COLOR", "calc", "currentColor", "dashed", "dotted", "double", "fill",
"groove", "hidden", "hsl", "hsla", "inherit", "initial", "inset",
"linear-gradient", "medium", "none", "outset", "radial-gradient", "repeat",
"repeating-linear-gradient", "repeating-radial-gradient", "rgb", "rgba",
"ridge", "round", "solid", "space", "stretch", "thick", "thin", "transparent",
"unset", "url"], "border-block-end": ["COLOR", "calc", "currentColor", "dashed",
"dotted", "double", "groove", "hidden", "hsl", "hsla", "inherit", "initial",
"inset", "medium", "none", "outset", "rgb", "rgba", "ridge", "solid", "thick",
"thin", "transparent", "unset"], "border-block-end-color": ["COLOR",
"currentColor", "hsl", "hsla", "inherit", "initial", "rgb", "rgba",
"transparent", "unset"], "border-block-end-style": ["dashed", "dotted",
"double", "groove", "hidden", "inherit", "initial", "inset", "none", "outset",
"ridge", "solid", "unset"], "border-block-end-width": ["calc", "inherit",
"initial", "medium", "thick", "thin", "unset"], "border-block-start": ["COLOR",
"calc", "currentColor", "dashed", "dotted", "double", "groove", "hidden", "hsl",
"hsla", "inherit", "initial", "inset", "medium", "none", "outset", "rgb",
"rgba", "ridge", "solid", "thick", "thin", "transparent", "unset"],
"border-block-start-color": ["COLOR", "currentColor", "hsl", "hsla", "inherit",
"initial", "rgb", "rgba", "transparent", "unset"], "border-block-start-style":
["dashed", "dotted", "double", "groove", "hidden", "inherit", "initial",
"inset", "none", "outset", "ridge", "solid", "unset"],
"border-block-start-width": ["calc", "inherit", "initial", "medium", "thick",
"thin", "unset"], "border-bottom": ["COLOR", "calc", "currentColor", "dashed",
"dotted", "double", "groove", "hidden", "hsl", "hsla", "inherit", "initial",
"inset", "medium", "none", "outset", "rgb", "rgba", "ridge", "solid", "thick",
"thin", "transparent", "unset"], "border-bottom-color": ["COLOR",
"currentColor", "hsl", "hsla", "inherit", "initial", "rgb", "rgba",
"transparent", "unset"], "border-bottom-left-radius": ["inherit", "initial",
"unset"], "border-bottom-right-radius": ["inherit", "initial", "unset"],
"border-bottom-style": ["dashed", "dotted", "double", "groove", "hidden",
"inherit", "initial", "inset", "none", "outset", "ridge", "solid", "unset"],
"border-bottom-width": ["calc", "inherit", "initial", "medium", "thick", "thin",
"unset"], "border-collapse": ["collapse", "inherit", "initial", "separate",
"unset"], "border-color": ["COLOR", "currentColor", "hsl", "hsla", "inherit",
"initial", "rgb", "rgba", "transparent", "unset"], "border-image": ["fill",
"inherit", "initial", "linear-gradient", "none", "radial-gradient", "repeat",
"repeating-linear-gradient", "repeating-radial-gradient", "round", "space",
"stretch", "unset", "url"], "border-image-outset": ["inherit", "initial",
"unset"], "border-image-repeat": ["inherit", "initial", "repeat", "round",
"space", "stretch", "unset"], "border-image-slice": ["fill", "inherit",
"initial", "unset"], "border-image-source": ["inherit", "initial",
"linear-gradient", "none", "radial-gradient", "repeating-linear-gradient",
"repeating-radial-gradient", "unset", "url"], "border-image-width": ["inherit",
"initial", "unset"], "border-inline-end": ["COLOR", "calc", "currentColor",
"dashed", "dotted", "double", "groove", "hidden", "hsl", "hsla", "inherit",
"initial", "inset", "medium", "none", "outset", "rgb", "rgba", "ridge", "solid",
"thick", "thin", "transparent", "unset"], "border-inline-end-color": ["COLOR",
"currentColor", "hsl", "hsla", "inherit", "initial", "rgb", "rgba",
"transparent", "unset"], "border-inline-end-style": ["dashed", "dotted",
"double", "groove", "hidden", "inherit", "initial", "inset", "none", "outset",
"ridge", "solid", "unset"], "border-inline-end-width": ["calc", "inherit",
"initial", "medium", "thick", "thin", "unset"], "border-inline-start": ["COLOR",
"calc", "currentColor", "dashed", "dotted", "double", "groove", "hidden", "hsl",
"hsla", "inherit", "initial", "inset", "medium", "none", "outset", "rgb",
"rgba", "ridge", "solid", "thick", "thin", "transparent", "unset"],
"border-inline-start-color": ["COLOR", "currentColor", "hsl", "hsla", "inherit",
"initial", "rgb", "rgba", "transparent", "unset"], "border-inline-start-style":
["dashed", "dotted", "double", "groove", "hidden", "inherit", "initial",
"inset", "none", "outset", "ridge", "solid", "unset"],
"border-inline-start-width": ["calc", "inherit", "initial", "medium", "thick",
"thin", "unset"], "border-left": ["COLOR", "calc", "currentColor", "dashed",
"dotted", "double", "groove", "hidden", "hsl", "hsla", "inherit", "initial",
"inset", "medium", "none", "outset", "rgb", "rgba", "ridge", "solid", "thick",
"thin", "transparent", "unset"], "border-left-color": ["COLOR", "currentColor",
"hsl", "hsla", "inherit", "initial", "rgb", "rgba", "transparent", "unset"],
"border-left-style": ["dashed", "dotted", "double", "groove", "hidden",
"inherit", "initial", "inset", "none", "outset", "ridge", "solid", "unset"],
"border-left-width": ["calc", "inherit", "initial", "medium", "thick", "thin",
"unset"], "border-radius": ["inherit", "initial", "unset"], "border-right":
["COLOR", "calc", "currentColor", "dashed", "dotted", "double", "groove",
"hidden", "hsl", "hsla", "inherit", "initial", "inset", "medium", "none",
"outset", "rgb", "rgba", "ridge", "solid", "thick", "thin", "transparent",
"unset"], "border-right-color": ["COLOR", "currentColor", "hsl", "hsla",
"inherit", "initial", "rgb", "rgba", "transparent", "unset"],
"border-right-style": ["dashed", "dotted", "double", "groove", "hidden",
"inherit", "initial", "inset", "none", "outset", "ridge", "solid", "unset"],
"border-right-width": ["calc", "inherit", "initial", "medium", "thick", "thin",
"unset"], "border-spacing": ["inherit", "initial", "unset"], "border-style":
["dashed", "dotted", "double", "groove", "hidden", "inherit", "initial",
"inset", "none", "outset", "ridge", "solid", "unset"], "border-top": ["COLOR",
"calc", "currentColor", "dashed", "dotted", "double", "groove", "hidden", "hsl",
"hsla", "inherit", "initial", "inset", "medium", "none", "outset", "rgb",
"rgba", "ridge", "solid", "thick", "thin", "transparent", "unset"],
"border-top-color": ["COLOR", "currentColor", "hsl", "hsla", "inherit",
"initial", "rgb", "rgba", "transparent", "unset"], "border-top-left-radius":
["inherit", "initial", "unset"], "border-top-right-radius": ["inherit",
"initial", "unset"], "border-top-style": ["dashed", "dotted", "double",
"groove", "hidden", "inherit", "initial", "inset", "none", "outset", "ridge",
"solid", "unset"], "border-top-width": ["calc", "inherit", "initial", "medium",
"thick", "thin", "unset"], "border-width": ["calc", "inherit", "initial",
"medium", "thick", "thin", "unset"], "bottom": ["auto", "calc", "inherit",
"initial", "unset"], "box-decoration-break": ["clone", "inherit", "initial",
"slice", "unset"], "box-shadow": ["inherit", "initial", "inset", "unset"],
"box-sizing": ["border-box", "content-box", "inherit", "initial", "unset"],
"caption-side": ["bottom", "bottom-outside", "inherit", "initial", "left",
"right", "top", "top-outside", "unset"], "caret-color": ["COLOR", "auto",
"currentColor", "hsl", "hsla", "inherit", "initial", "rgb", "rgba",
"transparent", "unset"], "clear": ["both", "inherit", "initial", "inline-end",
"inline-start", "left", "none", "right", "unset"], "clip": ["inherit",
"initial", "unset"], "clip-path": ["inherit", "initial", "unset"], "clip-rule":
["evenodd", "inherit", "initial", "nonzero", "unset"], "color": ["COLOR",
"currentColor", "hsl", "hsla", "inherit", "initial", "rgb", "rgba",
"transparent", "unset"], "color-adjust": ["economy", "exact", "inherit",
"initial", "unset"], "color-interpolation": ["auto", "inherit", "initial",
"linearrgb", "srgb", "unset"], "color-interpolation-filters": ["auto",
"inherit", "initial", "linearrgb", "srgb", "unset"], "column-count": ["auto",
"inherit", "initial", "unset"], "column-fill": ["auto", "balance", "inherit",
"initial", "unset"], "column-gap": ["calc", "inherit", "initial", "normal",
"unset"], "column-rule": ["COLOR", "calc", "currentColor", "dashed", "dotted",
"double", "groove", "hidden", "hsl", "hsla", "inherit", "initial", "inset",
"medium", "none", "outset", "rgb", "rgba", "ridge", "solid", "thick", "thin",
"transparent", "unset"], "column-rule-color": ["COLOR", "currentColor", "hsl",
"hsla", "inherit", "initial", "rgb", "rgba", "transparent", "unset"],
"column-rule-style": ["dashed", "dotted", "double", "groove", "hidden",
"inherit", "initial", "inset", "none", "outset", "ridge", "solid", "unset"],
"column-rule-width": ["calc", "inherit", "initial", "medium", "thick", "thin",
"unset"], "column-width": ["auto", "calc", "inherit", "initial", "unset"],
"columns": ["auto", "calc", "inherit", "initial", "unset"], "content":
["close-quote", "inherit", "initial", "no-close-quote", "no-open-quote",
"open-quote", "unset"], "counter-increment": ["inherit", "initial", "unset"],
"counter-reset": ["inherit", "initial", "unset"], "cursor": ["alias",
"all-scroll", "auto", "cell", "col-resize", "context-menu", "copy", "crosshair",
"default", "e-resize", "ew-resize", "grab", "grabbing", "help", "inherit",
"initial", "move", "n-resize", "ne-resize", "nesw-resize", "no-drop", "none",
"not-allowed", "ns-resize", "nw-resize", "nwse-resize", "pointer", "progress",
"row-resize", "s-resize", "se-resize", "sw-resize", "text", "unset",
"vertical-text", "w-resize", "wait", "zoom-in", "zoom-out"], "direction":
["inherit", "initial", "ltr", "rtl", "unset"], "display": ["block", "contents",
"flex", "flow-root", "grid", "inherit", "initial", "inline", "inline-block",
"inline-flex", "inline-grid", "inline-table", "list-item", "none", "ruby",
"ruby-base", "ruby-base-container", "ruby-text", "ruby-text-container", "table",
"table-caption", "table-cell", "table-column", "table-column-group",
"table-footer-group", "table-header-group", "table-row", "table-row-group",
"unset"], "dominant-baseline": ["alphabetic", "auto", "central", "hanging",
"ideographic", "inherit", "initial", "mathematical", "middle", "no-change",
"reset-size", "text-after-edge", "text-before-edge", "unset", "use-script"],
"empty-cells": ["hide", "inherit", "initial", "show", "unset"], "fill":
["context-fill", "context-stroke", "inherit", "initial", "unset"],
"fill-opacity": ["context-fill-opacity", "context-stroke-opacity", "inherit",
"initial", "unset"], "fill-rule": ["evenodd", "inherit", "initial", "nonzero",
"unset"], "filter": ["inherit", "initial", "unset"], "flex": ["auto", "calc",
"inherit", "initial", "unset"], "flex-basis": ["auto", "calc", "inherit",
"initial", "unset"], "flex-direction": ["column", "column-reverse", "inherit",
"initial", "row", "row-reverse", "unset"], "flex-flow": ["column",
"column-reverse", "inherit", "initial", "nowrap", "row", "row-reverse", "unset",
"wrap", "wrap-reverse"], "flex-grow": ["inherit", "initial", "unset"],
"flex-shrink": ["inherit", "initial", "unset"], "flex-wrap": ["inherit",
"initial", "nowrap", "unset", "wrap", "wrap-reverse"], "float": ["inherit",
"initial", "inline-end", "inline-start", "left", "none", "right", "unset"],
"flood-color": ["COLOR", "currentColor", "hsl", "hsla", "inherit", "initial",
"rgb", "rgba", "transparent", "unset"], "flood-opacity": ["inherit", "initial",
"unset"], "font": ["all-petite-caps", "all-small-caps", "auto", "bold",
"bolder", "calc", "caption", "common-ligatures", "condensed", "contextual",
"diagonal-fractions", "discretionary-ligatures", "expanded", "extra-condensed",
"extra-expanded", "full-width", "historical-forms", "historical-ligatures",
"icon", "inherit", "initial", "italic", "jis04", "jis78", "jis83", "jis90",
"large", "larger", "lighter", "lining-nums", "medium", "menu", "message-box",
"no-common-ligatures", "no-contextual", "no-discretionary-ligatures",
"no-historical-ligatures", "none", "normal", "oblique", "oldstyle-nums",
"ordinal", "petite-caps", "proportional-nums", "proportional-width", "ruby",
"semi-condensed", "semi-expanded", "simplified", "slashed-zero", "small",
"small-caps", "small-caption", "smaller", "stacked-fractions", "status-bar",
"sub", "super", "tabular-nums", "titling-caps", "traditional",
"ultra-condensed", "ultra-expanded", "unicase", "unset", "x-large", "x-small",
"xx-large", "xx-small"], "font-family": ["inherit", "initial", "unset"],
"font-feature-settings": ["inherit", "initial", "unset"], "font-kerning":
["auto", "inherit", "initial", "none", "normal", "unset"],
"font-language-override": ["inherit", "initial", "normal", "unset"],
"font-size": ["calc", "inherit", "initial", "large", "larger", "medium",
"small", "smaller", "unset", "x-large", "x-small", "xx-large", "xx-small"],
"font-size-adjust": ["inherit", "initial", "none", "unset"], "font-stretch":
["condensed", "expanded", "extra-condensed", "extra-expanded", "inherit",
"initial", "normal", "semi-condensed", "semi-expanded", "ultra-condensed",
"ultra-expanded", "unset"], "font-style": ["inherit", "initial", "italic",
"normal", "oblique", "unset"], "font-synthesis": ["inherit", "initial", "style",
"unset", "weight"], "font-variant": ["all-petite-caps", "all-small-caps",
"common-ligatures", "contextual", "diagonal-fractions",
"discretionary-ligatures", "full-width", "historical-forms",
"historical-ligatures", "inherit", "initial", "jis04", "jis78", "jis83",
"jis90", "lining-nums", "no-common-ligatures", "no-contextual",
"no-discretionary-ligatures", "no-historical-ligatures", "normal",
"oldstyle-nums", "ordinal", "petite-caps", "proportional-nums",
"proportional-width", "ruby", "simplified", "slashed-zero", "small-caps",
"stacked-fractions", "sub", "super", "tabular-nums", "titling-caps",
"traditional", "unicase", "unset"], "font-variant-alternates":
["historical-forms", "inherit", "initial", "unset"], "font-variant-caps":
["all-petite-caps", "all-small-caps", "inherit", "initial", "normal",
"petite-caps", "small-caps", "titling-caps", "unicase", "unset"],
"font-variant-east-asian": ["full-width", "inherit", "initial", "jis04",
"jis78", "jis83", "jis90", "proportional-width", "ruby", "simplified",
"traditional", "unset"], "font-variant-ligatures": ["common-ligatures",
"contextual", "discretionary-ligatures", "historical-ligatures", "inherit",
"initial", "no-common-ligatures", "no-contextual", "no-discretionary-ligatures",
"no-historical-ligatures", "unset"], "font-variant-numeric":
["diagonal-fractions", "inherit", "initial", "lining-nums", "oldstyle-nums",
"ordinal", "proportional-nums", "slashed-zero", "stacked-fractions",
"tabular-nums", "unset"], "font-variant-position": ["inherit", "initial",
"normal", "sub", "super", "unset"], "font-weight": ["bold", "bolder", "inherit",
"initial", "lighter", "normal", "unset"], "grid": ["calc", "column", "dense",
"inherit", "initial", "max-content", "min-content", "row", "unset"],
"grid-area": ["inherit", "initial", "unset"], "grid-auto-columns": ["inherit",
"initial", "max-content", "min-content", "unset"], "grid-auto-flow": ["column",
"dense", "inherit", "initial", "row", "unset"], "grid-auto-rows": ["inherit",
"initial", "max-content", "min-content", "unset"], "grid-column": ["inherit",
"initial", "unset"], "grid-column-end": ["inherit", "initial", "unset"],
"grid-column-gap": ["calc", "inherit", "initial", "unset"], "grid-column-start":
["inherit", "initial", "unset"], "grid-gap": ["calc", "inherit", "initial",
"unset"], "grid-row": ["inherit", "initial", "unset"], "grid-row-end":
["inherit", "initial", "unset"], "grid-row-gap": ["calc", "inherit", "initial",
"unset"], "grid-row-start": ["inherit", "initial", "unset"], "grid-template":
["inherit", "initial", "max-content", "min-content", "unset"],
"grid-template-areas": ["inherit", "initial", "unset"], "grid-template-columns":
["inherit", "initial", "max-content", "min-content", "unset"],
"grid-template-rows": ["inherit", "initial", "max-content", "min-content",
"unset"], "height": ["auto", "calc", "inherit", "initial", "unset"], "hyphens":
["auto", "inherit", "initial", "manual", "none", "unset"], "image-orientation":
["flip", "from-image", "inherit", "initial", "unset"], "image-rendering":
["auto", "inherit", "initial", "optimizequality", "optimizespeed", "unset"],
"ime-mode": ["active", "auto", "disabled", "inactive", "inherit", "initial",
"normal", "unset"], "inline-size": ["auto", "calc", "inherit", "initial",
"unset"], "isolation": ["auto", "inherit", "initial", "isolate", "unset"],
"justify-content": ["baseline", "center", "end", "flex-end", "flex-start",
"inherit", "initial", "last baseline", "left", "normal", "right",
"space-around", "space-between", "space-evenly", "start", "stretch", "unset"],
"justify-items": ["auto", "baseline", "center", "end", "flex-end", "flex-start",
"inherit", "initial", "last baseline", "left", "normal", "right", "self-end",
"self-start", "start", "stretch", "unset"], "justify-self": ["auto", "baseline",
"center", "end", "flex-end", "flex-start", "inherit", "initial", "last baseline",
"left", "normal", "right", "self-end", "self-start", "start",
"stretch", "unset"], "left": ["auto", "calc", "inherit", "initial", "unset"],
"letter-spacing": ["calc", "inherit", "initial", "normal", "unset"],
"lighting-color": ["COLOR", "currentColor", "hsl", "hsla", "inherit", "initial",
"rgb", "rgba", "transparent", "unset"], "line-height": ["calc", "inherit",
"initial", "normal", "unset"], "list-style": ["inherit", "initial", "inside",
"none", "outside", "unset", "url"], "list-style-image": ["inherit", "initial",
"none", "unset", "url"], "list-style-position": ["inherit", "initial", "inside",
"outside", "unset"], "list-style-type": ["inherit", "initial", "unset"],
"margin": ["auto", "calc", "inherit", "initial", "unset"], "margin-block-end":
["auto", "calc", "inherit", "initial", "unset"], "margin-block-start": ["auto",
"calc", "inherit", "initial", "unset"], "margin-bottom": ["auto", "calc",
"inherit", "initial", "unset"], "margin-inline-end": ["auto", "calc", "inherit",
"initial", "unset"], "margin-inline-start": ["auto", "calc", "inherit",
"initial", "unset"], "margin-left": ["auto", "calc", "inherit", "initial",
"unset"], "margin-right": ["auto", "calc", "inherit", "initial", "unset"],
"margin-top": ["auto", "calc", "inherit", "initial", "unset"], "marker":
["inherit", "initial", "none", "unset", "url"], "marker-end": ["inherit",
"initial", "none", "unset", "url"], "marker-mid": ["inherit", "initial", "none",
"unset", "url"], "marker-start": ["inherit", "initial", "none", "unset", "url"],
"mask": ["add", "alpha", "border-box", "bottom", "center", "contain",
"content-box", "cover", "exclude", "fill-box", "inherit", "initial",
"intersect", "left", "linear-gradient", "luminance", "match-source", "no-clip",
"no-repeat", "none", "padding-box", "radial-gradient", "repeat", "repeat-x",
"repeat-y", "repeating-linear-gradient", "repeating-radial-gradient", "right",
"round", "space", "stroke-box", "subtract", "top", "unset", "url", "view-box"],
"mask-clip": ["border-box", "content-box", "fill-box", "inherit", "initial",
"no-clip", "padding-box", "stroke-box", "unset", "view-box"], "mask-composite":
["add", "exclude", "inherit", "initial", "intersect", "subtract", "unset"],
"mask-image": ["inherit", "initial", "linear-gradient", "none",
"radial-gradient", "repeating-linear-gradient", "repeating-radial-gradient",
"unset", "url"], "mask-mode": ["alpha", "inherit", "initial", "luminance",
"match-source", "unset"], "mask-origin": ["border-box", "content-box",
"fill-box", "inherit", "initial", "padding-box", "stroke-box", "unset",
"view-box"], "mask-position": ["bottom", "center", "inherit", "initial", "left",
"right", "top", "unset"], "mask-position-x": ["bottom", "center", "inherit",
"initial", "left", "right", "top", "unset"], "mask-position-y": ["bottom",
"center", "inherit", "initial", "left", "right", "top", "unset"], "mask-repeat":
["inherit", "initial", "no-repeat", "repeat", "repeat-x", "repeat-y", "round",
"space", "unset"], "mask-size": ["contain", "cover", "inherit", "initial",
"unset"], "mask-type": ["alpha", "inherit", "initial", "luminance", "unset"],
"max-block-size": ["calc", "inherit", "initial", "none", "unset"], "max-height":
["calc", "inherit", "initial", "none", "unset"], "max-inline-size": ["calc",
"inherit", "initial", "none", "unset"], "max-width": ["calc", "inherit",
"initial", "none", "unset"], "min-block-size": ["auto", "calc", "inherit",
"initial", "unset"], "min-height": ["auto", "calc", "inherit", "initial",
"unset"], "min-inline-size": ["auto", "calc", "inherit", "initial", "unset"],
"min-width": ["auto", "calc", "inherit", "initial", "unset"], "mix-blend-mode":
["color", "color-burn", "color-dodge", "darken", "difference", "exclusion",
"hard-light", "hue", "inherit", "initial", "lighten", "luminosity", "multiply",
"normal", "overlay", "saturation", "screen", "soft-light", "unset"],
"object-fit": ["contain", "cover", "fill", "inherit", "initial", "none",
"scale-down", "unset"], "object-position": ["bottom", "center", "inherit",
"initial", "left", "right", "top", "unset"], "offset-block-end": ["auto",
"calc", "inherit", "initial", "unset"], "offset-block-start": ["auto", "calc",
"inherit", "initial", "unset"], "offset-inline-end": ["auto", "calc", "inherit",
"initial", "unset"], "offset-inline-start": ["auto", "calc", "inherit",
"initial", "unset"], "opacity": ["inherit", "initial", "unset"], "order":
["inherit", "initial", "unset"], "outline": ["COLOR", "auto", "calc",
"currentColor", "dashed", "dotted", "double", "groove", "hsl", "hsla",
"inherit", "initial", "inset", "medium", "none", "outset", "rgb", "rgba",
"ridge", "solid", "thick", "thin", "transparent", "unset"], "outline-color":
["COLOR", "currentColor", "hsl", "hsla", "inherit", "initial", "rgb", "rgba",
"transparent", "unset"], "outline-offset": ["calc", "inherit", "initial",
"unset"], "outline-style": ["auto", "dashed", "dotted", "double", "groove",
"inherit", "initial", "inset", "none", "outset", "ridge", "solid", "unset"],
"outline-width": ["calc", "inherit", "initial", "medium", "thick", "thin",
"unset"], "overflow": ["auto", "hidden", "inherit", "initial", "scroll",
"unset", "visible"], "overflow-wrap": ["break-word", "inherit", "initial",
"normal", "unset"], "overflow-x": ["auto", "hidden", "inherit", "initial",
"scroll", "unset", "visible"], "overflow-y": ["auto", "hidden", "inherit",
"initial", "scroll", "unset", "visible"], "padding": ["calc", "inherit",
"initial", "unset"], "padding-block-end": ["calc", "inherit", "initial",
"unset"], "padding-block-start": ["calc", "inherit", "initial", "unset"],
"padding-bottom": ["calc", "inherit", "initial", "unset"], "padding-inline-end":
["calc", "inherit", "initial", "unset"], "padding-inline-start": ["calc",
"inherit", "initial", "unset"], "padding-left": ["calc", "inherit", "initial",
"unset"], "padding-right": ["calc", "inherit", "initial", "unset"],
"padding-top": ["calc", "inherit", "initial", "unset"], "page-break-after":
["always", "auto", "avoid", "inherit", "initial", "left", "right", "unset"],
"page-break-before": ["always", "auto", "avoid", "inherit", "initial", "left",
"right", "unset"], "page-break-inside": ["auto", "avoid", "inherit", "initial",
"unset"], "paint-order": ["inherit", "initial", "unset"], "perspective":
["inherit", "initial", "none", "unset"], "perspective-origin": ["bottom",
"center", "inherit", "initial", "left", "right", "top", "unset"],
"place-content": ["baseline", "center", "end", "flex-end", "flex-start",
"inherit", "initial", "last baseline", "left", "normal", "right",
"space-around", "space-between", "space-evenly", "start", "stretch", "unset"],
"place-items": ["auto", "baseline", "center", "end", "flex-end", "flex-start",
"inherit", "initial", "last baseline", "left", "normal", "right", "self-end",
"self-start", "start", "stretch", "unset"], "place-self": ["auto", "baseline",
"center", "end", "flex-end", "flex-start", "inherit", "initial", "last baseline",
"left", "normal", "right", "self-end", "self-start", "start",
"stretch", "unset"], "pointer-events": ["all", "auto", "fill", "inherit",
"initial", "none", "painted", "stroke", "unset", "visible", "visiblefill",
"visiblepainted", "visiblestroke"], "position": ["absolute", "fixed", "inherit",
"initial", "relative", "static", "sticky", "unset"], "quotes": ["inherit",
"initial", "unset"], "resize": ["both", "horizontal", "inherit", "initial",
"none", "unset", "vertical"], "right": ["auto", "calc", "inherit", "initial",
"unset"], "ruby-align": ["center", "inherit", "initial", "space-around",
"space-between", "start", "unset"], "ruby-position": ["inherit", "initial",
"over", "under", "unset"], "scroll-behavior": ["auto", "inherit", "initial",
"smooth", "unset"], "scroll-snap-coordinate": ["bottom", "center", "inherit",
"initial", "left", "right", "top", "unset"], "scroll-snap-destination":
["bottom", "center", "inherit", "initial", "left", "right", "top", "unset"],
"scroll-snap-points-x": ["inherit", "initial", "unset"], "scroll-snap-points-y":
["inherit", "initial", "unset"], "scroll-snap-type": ["inherit", "initial",
"mandatory", "none", "proximity", "unset"], "scroll-snap-type-x": ["inherit",
"initial", "mandatory", "none", "proximity", "unset"], "scroll-snap-type-y":
["inherit", "initial", "mandatory", "none", "proximity", "unset"],
"shape-rendering": ["auto", "crispedges", "geometricprecision", "inherit",
"initial", "optimizespeed", "unset"], "stop-color": ["COLOR", "currentColor",
"hsl", "hsla", "inherit", "initial", "rgb", "rgba", "transparent", "unset"],
"stop-opacity": ["inherit", "initial", "unset"], "stroke": ["context-fill",
"context-stroke", "inherit", "initial", "unset"], "stroke-dasharray":
["context-value", "inherit", "initial", "unset"], "stroke-dashoffset":
["context-value", "inherit", "initial", "unset"], "stroke-linecap": ["butt",
"inherit", "initial", "round", "square", "unset"], "stroke-linejoin": ["bevel",
"inherit", "initial", "miter", "round", "unset"], "stroke-miterlimit":
["inherit", "initial", "unset"], "stroke-opacity": ["context-fill-opacity",
"context-stroke-opacity", "inherit", "initial", "unset"], "stroke-width":
["context-value", "inherit", "initial", "unset"], "table-layout": ["auto",
"fixed", "inherit", "initial", "unset"], "text-align": ["center", "end",
"inherit", "initial", "justify", "left", "right", "start", "unset"],
"text-align-last": ["auto", "center", "end", "inherit", "initial", "justify",
"left", "right", "start", "unset"], "text-anchor": ["end", "inherit", "initial",
"middle", "start", "unset"], "text-combine-upright": ["all", "digits",
"inherit", "initial", "none", "unset"], "text-decoration": ["COLOR", "blink",
"currentColor", "dashed", "dotted", "double", "hsl", "hsla", "inherit",
"initial", "line-through", "none", "overline", "rgb", "rgba", "solid",
"transparent", "underline", "unset", "wavy"], "text-decoration-color": ["COLOR",
"currentColor", "hsl", "hsla", "inherit", "initial", "rgb", "rgba",
"transparent", "unset"], "text-decoration-line": ["blink", "inherit", "initial",
"line-through", "none", "overline", "underline", "unset"],
"text-decoration-style": ["dashed", "dotted", "double", "inherit", "initial",
"solid", "unset", "wavy"], "text-emphasis": ["COLOR", "currentColor", "hsl",
"hsla", "inherit", "initial", "rgb", "rgba", "transparent", "unset"],
"text-emphasis-color": ["COLOR", "currentColor", "hsl", "hsla", "inherit",
"initial", "rgb", "rgba", "transparent", "unset"], "text-emphasis-position":
["inherit", "initial", "left", "over", "right", "under", "unset"],
"text-emphasis-style": ["inherit", "initial", "unset"], "text-indent": ["calc",
"inherit", "initial", "unset"], "text-justify": ["auto", "distribute",
"inherit", "initial", "inter-character", "inter-word", "none", "unset"],
"text-orientation": ["inherit", "initial", "mixed", "sideways",
"sideways-right", "unset", "upright"], "text-overflow": ["clip", "ellipsis",
"inherit", "initial", "unset"], "text-rendering": ["auto", "geometricprecision",
"inherit", "initial", "optimizelegibility", "optimizespeed", "unset"],
"text-shadow": ["inherit", "initial", "unset"], "text-transform": ["capitalize",
"full-width", "inherit", "initial", "lowercase", "none", "unset", "uppercase"],
"top": ["auto", "calc", "inherit", "initial", "unset"], "touch-action": ["auto",
"inherit", "initial", "manipulation", "none", "pan-x", "pan-y", "unset"],
"transform": ["inherit", "initial", "unset"], "transform-box": ["border-box",
"fill-box", "inherit", "initial", "unset", "view-box"], "transform-origin":
["bottom", "center", "inherit", "initial", "left", "right", "top", "unset"],
"transform-style": ["flat", "inherit", "initial", "preserve-3d", "unset"],
"transition": ["all", "cubic-bezier", "ease", "ease-in", "ease-in-out",
"ease-out", "inherit", "initial", "linear", "none", "step-end", "step-start",
"steps", "unset"], "transition-delay": ["inherit", "initial", "unset"],
"transition-duration": ["inherit", "initial", "unset"], "transition-property":
["all", "inherit", "initial", "none", "unset"], "transition-timing-function":
["cubic-bezier", "ease", "ease-in", "ease-in-out", "ease-out", "inherit",
"initial", "linear", "step-end", "step-start", "steps", "unset"],
"unicode-bidi": ["bidi-override", "embed", "inherit", "initial", "isolate",
"isolate-override", "normal", "plaintext", "unset"], "vector-effect":
["inherit", "initial", "non-scaling-stroke", "none", "unset"], "vertical-align":
["baseline", "bottom", "calc", "inherit", "initial", "middle", "sub", "super",
"text-bottom", "text-top", "top", "unset"], "visibility": ["collapse", "hidden",
"inherit", "initial", "unset", "visible"], "white-space": ["inherit", "initial",
"normal", "nowrap", "pre", "pre-line", "pre-wrap", "unset"], "width": ["auto",
"calc", "inherit", "initial", "unset"], "will-change": ["inherit", "initial",
"unset"], "word-break": ["break-all", "inherit", "initial", "keep-all",
"normal", "unset"], "word-spacing": ["calc", "inherit", "initial", "normal",
"unset"], "word-wrap": ["break-word", "inherit", "initial", "normal", "unset"],
"writing-mode": ["horizontal-tb", "inherit", "initial", "lr", "lr-tb", "rl",
"rl-tb", "sideways-lr", "sideways-rl", "tb", "tb-rl", "unset", "vertical-lr",
"vertical-rl"], "z-index": ["auto", "inherit", "initial", "unset"]}
